name: thibolt
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  circular_countdown_timer: ^0.2.3
  audioplayers: ^5.2.1
  drag_and_drop_lists: ^0.3.3


dev_dependencies:
  icons_launcher: ^2.1.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: URWGothic
      fonts:
        - asset: assets/fonts/URWGothic-Book.otf
        - asset: assets/fonts/URWGothic-BookOblique.otf
          style: italic
        - asset: assets/fonts/URWGothic-Demi.otf
          weight: 700
    - family: BebasKai
      fonts:
        - asset: assets/fonts/BebasKai.otf
